[[article]]
slug = "005"
file = "005.md"
title = "005｜Rust 1.56.0 - 2021 Editon 更新"
author = "Binlogo"
cover = "/static/season-2/005/rust.png"
pub_date = "2021-10-31"
publish = true
featured = true

[[article]]
slug = "006"
file = "006.md"
title = "006｜如何学习编译器： LLVM"
author = "Binlogo"
cover = "/static/season-2/006/llvm.webp"
pub_date = "2021-11-07"
publish = true
featured = true

[[article]]
slug = "007"
file = "007.md"
title = "007｜系统编程的安全性"
author = "Binlogo"
cover = "/static/season-2/007/stanford-university-logo.png"
pub_date = "2021-11-14"
publish = true
featured = true

[[article]]
slug = "008"
file = "008.md"
title = "008｜第二大脑体系结构新升级"
author = "Binlogo"
cover = "/static/season-2/008/second-brain-structure.png"
pub_date = "2021-11-21"
publish = true
featured = true
